/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.glitchybyte.gradle.plugin.buildinfoplugin

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'com.glitchybyte.glitchybuild.greeting' plugin.
 */
class BuildInfoPluginFunctionalTest {

    @Test
    fun canRunTask() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("rootProject.name = \"MyFunctionalTest\"")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('com.glitchybyte.gradle.plugin.buildinfoplugin')
            }
            group = "myGroup"
            version = "5.0.8"
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments(/*BuildInfo("myGroup", "myName", "myVersion")*/)
        runner.withProjectDir(projectDir)
        val result = runner.build();

        // Verify the result
//        assertTrue(result.output.contains("Captured: "))
        assertTrue(true)
    }
}
